-- MySQL Script generated by MySQL Workbench
-- 05/25/19 20:25:39
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD_SRP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_SRP` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BD_SRP` ;

-- -----------------------------------------------------
-- Table `BD_SRP`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SRP`.`Carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `Carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SRP`.`Tipo_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SRP`.`Tipo_proyecto` (
  `idTipo_proyecto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SRP`.`Control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SRP`.`Control` (
  `idControl` INT NOT NULL AUTO_INCREMENT,
  `Avance` DECIMAL(3) NOT NULL,
  PRIMARY KEY (`idControl`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SRP`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SRP`.`Proyectos` (
  `idProyectos` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Ruta` VARCHAR(45) NOT NULL,
  `idCarrera` INT NOT NULL,
  `idTipo_proyecto` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `idControl` INT NOT NULL,
  PRIMARY KEY (`idProyectos`),
  INDEX `idCarrera_idx` (`idCarrera` ASC),
  INDEX `idTipo_proyecto_idx` (`idTipo_proyecto` ASC),
  INDEX `idControl_idx` (`idControl` ASC),
  CONSTRAINT `idCarrera`
    FOREIGN KEY (`idCarrera`)
    REFERENCES `BD_SRP`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTipo_proyecto`
    FOREIGN KEY (`idTipo_proyecto`)
    REFERENCES `BD_SRP`.`Tipo_proyecto` (`idTipo_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idControl`
    FOREIGN KEY (`idControl`)
    REFERENCES `BD_SRP`.`Control` (`idControl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SRP`.`Status_profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SRP`.`Status_profesor` (
  `idStatus_profesor` INT NOT NULL AUTO_INCREMENT,
  `idProyectos` INT NOT NULL,
  `Status_profesor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatus_profesor`),
  INDEX `idProyectos_idx` (`idProyectos` ASC),
  CONSTRAINT `idProyecto`
    FOREIGN KEY (`idProyectos`)
    REFERENCES `BD_SRP`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SRP`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SRP`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Rol` INT NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_SRP`.`Proyecto-usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_SRP`.`Proyecto-usuarios` (
  `idProyecto-usuarios` INT NOT NULL AUTO_INCREMENT,
  `idProyectos` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idProyecto-usuarios`),
  INDEX `idProyectos_idx` (`idProyectos` ASC),
  INDEX `idUsuarios_idx` (`idUsuarios` ASC),
  CONSTRAINT `idProyectos`
    FOREIGN KEY (`idProyectos`)
    REFERENCES `BD_SRP`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuarios`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `BD_SRP`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
